[package]
name = "day1128"
version = "0.1.0"
authors = ["tanhao1410 <2528865013@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
